# Cloud Build configuration for kernel-browser
steps:
  # Step 1: Verify kernel-images directory exists
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking kernel-images directory..."
        ls -la kernel-images/
        echo "Checking server directory..."
        ls -la kernel-images/server/

  # Step 2: Pull previous image for caching (ignore errors if doesn't exist)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Attempting to pull previous image for caching..."
        docker pull us-docker.pkg.dev/$PROJECT_ID/gcr.io/kernel-browser:latest || echo "No previous image found for caching"

  # Step 3: Build the Docker image with caching (using cloudrun Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--file'
      - 'Dockerfile.cloudrun'
      - '--cache-from'
      - 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/kernel-browser:latest'
      - '--build-arg'
      - 'CACHE_BUST=$BUILD_ID'
      - '--tag'
      - 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/kernel-browser:latest'
      - '.'
    timeout: '3600s'  # Allow 1 hour for build (it's a large image)

  # Step 4: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/kernel-browser:latest'

  # Step 5: Deploy to Cloud Run with appropriate service.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if Twilio secrets exist and choose appropriate service file
        if gcloud secrets describe twilio-account-sid --project=$PROJECT_ID >/dev/null 2>&1 && \
           gcloud secrets describe twilio-auth-token --project=$PROJECT_ID >/dev/null 2>&1; then
          echo "Using service-secrets.yaml with Secret Manager references"
          SERVICE_FILE="service-secrets.yaml"
        else
          echo "Using standard service.yaml (secrets not configured)"
          SERVICE_FILE="service.yaml"
        fi
        
        # Update project ID in the chosen service file
        cp $$SERVICE_FILE temp-service.yaml
        sed -i "s/PROJECT_ID/$PROJECT_ID/g" temp-service.yaml
        
        echo "Deploying with: $$SERVICE_FILE"
        cat temp-service.yaml
        
        # Deploy to Cloud Run
        gcloud run services replace temp-service.yaml \
          --region=us-central1 \
          --quiet

  # Step 6: Update traffic to latest revision
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'kernel-browser'
      - '--to-latest'
      - '--region=us-central1'
      - '--quiet'

  # Step 7: Get the service URL
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'describe'
      - 'kernel-browser'
      - '--region=us-central1'
      - '--format=table(status.url)'

# Build timeout (allow 2 hours total)
timeout: '7200s'

# Build options
options:
  # Use high CPU machine for faster builds
  machineType: 'E2_HIGHCPU_32'
  # Allocate disk space for the large build
  diskSizeGb: 100

# Images to be pushed to Artifact Registry
images:
  - 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/kernel-browser:latest'


# Tags for organization
tags:
  - 'kernel-browser'
  - 'chrome-automation'
  - 'webrtc'