apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kernel-browser
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # Use second generation execution environment
        run.googleapis.com/execution-environment: gen2
        # Disable CPU throttling for consistent performance
        run.googleapis.com/cpu-throttling: "false"
        # Increase startup timeout to 10 minutes for complex service startup
        run.googleapis.com/timeout: "600"
        # Auto-scaling settings
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      # Allow multiple concurrent requests (browser can handle multiple tabs/requests)
      containerConcurrency: 10
      # 1 hour timeout for long browser sessions
      timeoutSeconds: 3600
      # Service account for GCP access
      serviceAccountName: kernel-browser-sa
      containers:
      - name: kernel-browser
        # This will be set during deployment
        image: us-docker.pkg.dev/PROJECT_ID/gcr.io/kernel-browser:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            # 2 CPU cores (within quota limits)
            cpu: "2"
            # 2GiB memory (reduced to prevent DevTools crashes)
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        env:
        # Enable WebRTC for live viewing
        - name: ENABLE_WEBRTC
          value: "true"
        # Run as non-root user (Cloud Run requirement)
        - name: RUN_AS_ROOT
          value: "false"
        # Chrome optimizations for Cloud Run
        - name: CHROMIUM_FLAGS
          value: "--user-data-dir=/home/kernel/user-data --disable-dev-shm-usage --disable-gpu --start-maximized --disable-software-rasterizer --remote-allow-origins=* --no-sandbox --disable-setuid-sandbox --disable-features=VizDisplayCompositor"
        # Display configuration
        - name: DISPLAY_NUM
          value: "1"
        - name: HEIGHT
          value: "768"
        - name: WIDTH
          value: "1024"
        # Twilio API Key credentials from Secret Manager
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: twilio-account-sid
              key: latest
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: twilio-auth-token
              key: latest
        # Dynamic TURN credentials will be generated using above secrets
        # The twilio-credential-updater.sh script will use these at startup
        - name: NEKO_ICESERVERS
          value: 'DYNAMIC'  # Placeholder - will be replaced by twilio-credential-updater.sh
        # TCP-only WebRTC configuration for Cloud Run
        - name: NEKO_WEBRTC_TCPMUX
          value: "0"  # Disable TCP multiplexing (nginx handles port 8080)
        - name: NEKO_WEBRTC_ICE_LITE
          value: "true"  # Use ICE-Lite mode for server
        - name: NEKO_WEBRTC_ICE_SERVERS_ONLY_TURN
          value: "true"  # Only use TURN servers, no STUN
        # Optional: Google Cloud Storage bucket for recordings
        - name: GCS_BUCKET
          value: "kernel-browser-recordings"
        # API configuration
        - name: KERNEL_IMAGES_API_PORT
          value: "10001"
        - name: KERNEL_IMAGES_API_FRAME_RATE
          value: "10"
        - name: KERNEL_IMAGES_API_MAX_SIZE_MB
          value: "500"
        - name: KERNEL_IMAGES_API_OUTPUT_DIR
          value: "/tmp/recordings"
        # Eval-Server configuration
        - name: EVAL_SERVER_WS_PORT
          value: "8082"
        - name: EVAL_SERVER_HTTP_PORT
          value: "8083"
        - name: EVAL_SERVER_HOST
          value: "127.0.0.1"
        # Force new revision
        - name: DEPLOYMENT_VERSION
          value: "v16-eval-server-with-nodejs"
  traffic:
  - percent: 100
    latestRevision: true